version: "3.8"

services:
  postgres:
    container_name: nest-postgres
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
      PG_DATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres

  cache:
    container_name: nest-redis
    image: redis:6
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./data/redis:/data
